name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install "Shippori Mincho B1"
        uses: SnO2WMaN/install-fontsource-action@v0.0.2
        with:
          font-name: Shippori Mincho B1
      - name: Install "Shippori Antique B1"
        uses: SnO2WMaN/install-fontsource-action@v0.0.2
        with:
          font-name: Shippori Antique B1
      - name: Install "Julia Mono"
        uses: SnO2WMaN/install-juliamono-action@v0.0.1
      - uses: typst-community/setup-typst@v4
      - run: typst fonts
      - run: gh repo view --json licenseInfo,url > meta.json
        env:
          GH_TOKEN: ${{ github.token }}
      - run: typst compile main.typ main.pdf
      - name: Create page directory
        run: |
          mkdir _pages
          mv ./main.pdf ./_pages/main.pdf
          echo "<meta http-equiv=\"refresh\" content=\"0;URL='$(gh api "repos/$GITHUB_REPOSITORY" --jq '.html_url')'\">" > ./_pages/index.html
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _pages/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
